swsets :
   - core
mns : ThematicMNS
buildmode : local
apps_root : $HOME/.local/resif 
release : HEAD
git_ebblocks: https://github.com/ULHPC/easybuild-easyblocks|resif-v1.4.0
git_ebconfigs: https://github.com/ULHPC/easybuild-easyconfigs|resif-v1.4.0
git_ebframework: https://github.com/ULHPC/easybuild-framework|resif-v1.4.0
