# Toolchains in core:
# ictce-5.3.0
# goolf-1.4.10 # Not on Jessie
core:
  - ABINIT-7.2.1-x86_64_linux_gnu4.5.eb
  - ABySS-1.3.4-ictce-5.3.0-Python-2.7.3.eb
  - ABySS-1.3.4-goolf-1.4.10-Python-2.7.3.eb
  - ABySS-1.3.6-goolf-1.4.10-Python-2.7.5.eb # easyconfig fix: libreadline fix: preconfigopts = " LDFLAGS='-ltinfo' "
  - ASE-3.6.0.2515-ictce-5.3.0-Python-2.7.3.eb
  - ASE-3.6.0.2515-goolf-1.4.10-Python-2.7.3.eb
  - Autoconf-2.69-goolf-1.4.10.eb
  - Autoconf-2.69-ictce-5.3.0.eb
  - Automake-1.13.4-goolf-1.4.10.eb
  - Automake-1.14-ictce-5.3.0.eb
  - Boost-1.53.0-ictce-5.3.0-Python-2.7.5.eb
  - Boost-1.53.0-goolf-1.4.10.eb
  - Bowtie2-2.2.2-goolf-1.4.10.eb
  - Bowtie2-2.0.2-ictce-5.3.0.eb
  - CMake-2.8.12-goolf-1.4.10.eb
  - CMake-2.8.12-ictce-5.3.0.eb
  - CUDA-5.5.22.eb 
  - Cufflinks-2.0.2-goolf-1.4.10.eb # Sources changed location (project website moved) (In fact, sources from the new site don't work, use old one that are on the server) Fix applied in last EB version: preconfigopts = 'CPPFLAGS="-I$EBROOTEIGEN/include $CPPFLAGS" LDFLAGS="-lboost_system $LDFLAGS" '
  - Cufflinks-2.0.2-ictce-5.3.0.eb # Sources changed location (project website moved) (In fact, sources from the new site don't work, use old one that are on the server) Fix applied in last EB version: preconfigopts = 'CPPFLAGS="-I$EBROOTEIGEN/include $CPPFLAGS" LDFLAGS="-lboost_system $LDFLAGS" '
  - Eigen-3.1.4-goolf-1.4.10.eb
  - Eigen-3.1.4-ictce-5.3.0.eb
  - ESPResSo-3.1.1-goolf-1.4.10-parallel.eb
  - ESPResSo-3.1.1-goolf-1.4.10-serial.eb
  - ESPResSo-3.1.1-ictce-5.3.0-parallel.eb
  - ESPResSo-3.1.1-ictce-5.3.0-serial.eb
  - GDB-7.5.1-goolf-1.4.10.eb
  - gnuplot-4.6.0-goolf-1.4.10.eb
  - gnuplot-4.6.0-ictce-5.3.0.eb
  - GPAW-0.9.0.8965-goolf-1.4.10-Python-2.7.3.eb
  - GPAW-0.9.0.8965-ictce-5.3.0-Python-2.7.3.eb
  - GROMACS-4.6.5-goolf-1.4.10-mt.eb
  - GROMACS-4.6.1-ictce-5.3.0-mt.eb
  - GROMACS-4.6.1-ictce-5.3.0-hybrid.eb
  - h5utils-1.12.1-goolf-1.4.10.eb # Download sources separately for byacc and ncurses from "invisible-island.net"
  - h5utils-1.12.1-ictce-5.3.0.eb # Download sources separately for byacc and ncurses from "invisible-island.net"
  - Lmod-5.8-GCC-4.8.2.eb
  - matplotlib-1.3.1-goolf-1.4.10-Python-2.7.6.eb
  - matplotlib-1.3.0-ictce-5.3.0-Python-2.7.5.eb
  - Meep-1.2-goolf-1.4.10.eb
  - Meep-1.2-ictce-5.3.0.eb
  - netCDF-4.2-goolf-1.4.10.eb
  - netCDF-4.2-ictce-5.3.0.eb
  - netCDF-C++-4.2-goolf-1.4.10.eb
  - netCDF-C++-4.2-ictce-5.3.0.eb # Problem on cluster: MPI linking problem (Problem with gpfs actually, fix: remove -gpfs in the netCDF (4.2.1.1) easyconfig)
  - netCDF-Fortran-4.2-goolf-1.4.10.eb
  - netCDF-Fortran-4.2-ictce-5.3.0.eb # Problem on cluster: MPI linking problem (Problem with gpfs actually, fix: remove -gpfs in the netCDF (4.2.1.1) easyconfig)
  - numpy-1.8.0-ictce-5.3.0-Python-2.7.5.eb
  - numpy-1.7.1-goolf-1.4.10-Python-2.7.3.eb
  - OpenFOAM-2.3.0-goolf-1.4.10.eb
  - OpenFOAM-2.3.0-ictce-5.3.0.eb
  # Sanity check fails - Perl-5.16.3-goolf-1.4.10.eb # Problem with some modules
  - Perl-5.16.3-goolf-1.4.10-bare.eb
  # Sanity check fails - Perl-5.16.3-ictce-5.3.0.eb # Problem with some modules
  - Perl-5.16.3-ictce-5.3.0-bare.eb
  - Python-2.7.6-goolf-1.4.10.eb
  - Python-2.7.5-ictce-5.3.0.eb
  - Python-3.3.2-goolf-1.4.10.eb
  - Python-3.3.2-ictce-5.3.0.eb
  - QuantumESPRESSO-5.0.2-goolf-1.4.10.eb
  - QuantumESPRESSO-5.0.2-goolf-1.4.10-hybrid.eb
  - QuantumESPRESSO-5.0.2-ictce-5.3.0.eb
  - QuantumESPRESSO-5.0.2-ictce-5.3.0-hybrid.eb
  - R-3.0.2-goolf-1.4.10.eb # Download Java sources separately (normal behavior in EasyBuild) + some dependencies don't download correctly. Had to get them in the cluster's sources + pim changed version from 1.1.5.4 to 1.1.5.6 (change made in the eb file)
  - R-3.0.2-ictce-5.3.0.eb # Download Java sources separately (normal behavior in EasyBuild) + some dependencies don't download correctly. Had to get them in the cluster's sources + pim changed version from 1.1.5.4 to 1.1.5.6 (change made in the eb file)
  - R-3.0.2-ictce-5.3.0-bare.eb # Download Java sources separately (normal behavior in EasyBuild)
  - scipy-0.13.0-goolf-1.4.10-Python-2.7.3.eb
  - scipy-0.12.0-ictce-5.3.0-Python-2.7.3.eb
  # - Valgrind-3.8.1-goolf-1.4.10.eb # Bug linked to Debian having changed some files' location, fix: cd /usr/include && ln -s linux/a.out.h .
  - XCrySDen-1.5.53-goolf-1.4.10.eb # changing dependencies in XCrySDen to libXmu-dev and in Mesa to libX11-dev x11proto-core-dev libXdamage-dev libXext-dev libXfixes-dev + downloading MesaLib sources manually.
  - XCrySDen-1.5.53-ictce-5.3.0.eb # changing dependencies in XCrySDen to libXmu-dev and in Mesa to libX11-dev x11proto-core-dev libXdamage-dev libXext-dev libXfixes-dev + downloading MesaLib sources manually.
  # Custom module, see how it truly works- MATLAB-2013a.eb # eb file only in ULHPC repo. jdk-7u10 and matlab sources to download manually
  - TotalView-8.12.0-0-linux-x86-64.eb # sources to get manually
  # Fail - ABAQUS-6.12.1-linux-x86_64.eb # Need to be adapted: change sources name (note: sources have to be downloaded manually), change version and name to have a match between sources and easyconfig
ulhpc:
  - Autoconf-2.69-gcccuda-2.6.10.eb
  - Automake-1.14-gcccuda-2.6.10.eb
  - Automake-1.14.1-GCC-4.8.2.eb
  - Boost-1.55.0.eb
  # GCC-4.8.3 sources to download manually - CMake-3.0.0-GCC-4.8.3.eb
  - CUDA-5.5.22-GCC-4.8.2.eb
issue_Perl:
  - Perl-5.16.3-goolf-1.4.10.eb
  - Perl-5.16.3-ictce-5.3.0.eb
issue_Valgrind:
  - Valgrind-3.8.1-goolf-1.4.10.eb
issue_MATLAB:
  - MATLAB-2013a.eb
issue_ABAQUS:
  - ABAQUS-6.12.1-linux-x86_64.eb
issue_CMake:
  - CMake-3.0.0-GCC-4.8.3.eb