# Toolchains in core:
# ictce-5.3.0
# goolf-1.4.10
# ictce-7.3.5

core:
  - ABINIT-7.2.1-x86_64_linux_gnu4.5.eb
  - ABySS-1.3.4-ictce-5.3.0-Python-2.7.3.eb # easyconfig fix: libreadline-6.2-goolf-1.4.10 fix: preconfigopts = " LDFLAGS='-ltinfo' "
  - ABySS-1.3.4-goolf-1.4.10-Python-2.7.3.eb # easyconfig fix: libreadline-6.2-goolf-1.4.10 fix: preconfigopts = " LDFLAGS='-ltinfo' "
  - ABySS-1.5.2-goolf-1.4.10.eb
  # Not on Debian (Python 2.7.5 problem) - ABySS-1.3.6-goolf-1.4.10-Python-2.7.5.eb
  - ASE-3.6.0.2515-ictce-5.3.0-Python-2.7.3.eb
  - ASE-3.6.0.2515-goolf-1.4.10-Python-2.7.3.eb
  - ASE-3.9.0.4465-ictce-7.3.5-Python-2.7.10.eb
  - Autoconf-2.69-goolf-1.4.10.eb
  - Autoconf-2.69-ictce-5.3.0.eb
  - Automake-1.13.4-goolf-1.4.10.eb
  - Automake-1.14-ictce-5.3.0.eb
  - BioPerl-1.6.1-ictce-5.3.0-Perl-5.16.3.eb
  - BioPerl-1.6.1-goolf-1.4.10-Perl-5.16.3.eb
  - Boost-1.53.0-ictce-5.3.0-Python-2.7.5.eb
  - Boost-1.53.0-goolf-1.4.10.eb
  - Bowtie2-2.2.2-goolf-1.4.10.eb
  - Bowtie2-2.0.2-ictce-5.3.0.eb
  - CMake-2.8.12-goolf-1.4.10.eb
  - CMake-2.8.12-ictce-5.3.0.eb
  - CUDA-5.5.22.eb 
  # Cufflinks fix: went upstream
  - Cufflinks-2.0.2-goolf-1.4.10.eb # Sources changed location (project website moved) (In fact, sources from the new site don't work, use old one that are on the server) Fix applied in last EB version: preconfigopts = 'CPPFLAGS="-I$EBROOTEIGEN/include $CPPFLAGS" LDFLAGS="-lboost_system $LDFLAGS" '
  - Cufflinks-2.0.2-ictce-5.3.0.eb # Sources changed location (project website moved) (In fact, sources from the new site don't work, use old one that are on the server) Fix applied in last EB version: preconfigopts = 'CPPFLAGS="-I$EBROOTEIGEN/include $CPPFLAGS" LDFLAGS="-lboost_system $LDFLAGS" '
  - Cufflinks-2.2.1-goolf-1.4.10.eb
  - Eigen-3.1.4-goolf-1.4.10.eb
  - Eigen-3.1.4-ictce-5.3.0.eb
  - ESPResSo-3.1.1-goolf-1.4.10-parallel.eb
  - ESPResSo-3.1.1-goolf-1.4.10-serial.eb
  - ESPResSo-3.1.1-ictce-5.3.0-parallel.eb
  - ESPResSo-3.1.1-ictce-5.3.0-serial.eb
  - GDB-7.5.1-goolf-1.4.10.eb
  - gnuplot-4.6.0-goolf-1.4.10.eb
  - gnuplot-4.6.0-ictce-5.3.0.eb
  - GPAW-0.9.0.8965-goolf-1.4.10-Python-2.7.3.eb
  - GPAW-0.9.0.8965-ictce-5.3.0-Python-2.7.3.eb
  - GROMACS-4.6.5-goolf-1.4.10-hybrid.eb # regressiontests links broken, these sources have to be downloaded beforehand. # NOT TESTED YET
  - GROMACS-4.6.5-goolf-1.4.10-mt.eb # regressiontests links broken, these sources have to be downloaded beforehand.
  - GROMACS-4.6.1-ictce-5.3.0-mt.eb # regressiontests links broken, these sources have to be downloaded beforehand.
  - GROMACS-4.6.1-ictce-5.3.0-hybrid.eb # regressiontests links broken, these sources have to be downloaded beforehand.
  - h5utils-1.12.1-goolf-1.4.10.eb # Download sources separately for byacc and ncurses from "invisible-island.net"
  - h5utils-1.12.1-ictce-5.3.0.eb # Download sources separately for byacc and ncurses from "invisible-island.net"
  - ictce-7.3.5.eb
  - Lmod-5.8-GCC-4.8.2.eb # EasyConfig not in the current repo, add it.
  - matplotlib-1.3.1-goolf-1.4.10-Python-2.7.6.eb
  - matplotlib-1.4.3-ictce-7.3.5-Python-2.7.10.eb
  - Meep-1.2-goolf-1.4.10.eb
  - Meep-1.2-ictce-5.3.0.eb
  - mpiBLAST-1.6.0-ictce-7.3.5.eb
  - netCDF-4.2-goolf-1.4.10.eb
  - netCDF-4.2-ictce-5.3.0.eb
  - netCDF-C++-4.2-goolf-1.4.10.eb
  - netCDF-C++-4.2-ictce-5.3.0.eb # Problem on cluster: MPI linking problem (Problem with gpfs actually, fix: remove -gpfs in the netCDF (4.2.1.1) easyconfig)
  - netCDF-Fortran-4.2-goolf-1.4.10.eb
  - netCDF-Fortran-4.2-ictce-5.3.0.eb # Problem on cluster: MPI linking problem (Problem with gpfs actually, fix: remove -gpfs in the netCDF (4.2.1.1) easyconfig)
  - numpy-1.8.0-ictce-5.3.0-Python-2.7.5.eb
  - numpy-1.7.1-goolf-1.4.10-Python-2.7.3.eb
  - OpenFOAM-2.3.0-goolf-1.4.10.eb
  - OpenFOAM-2.3.0-ictce-5.3.0.eb
  - Perl-5.16.3-goolf-1.4.10.eb # Perl problem comes from the shebang being too long. This problem should disappear at release since the rootinstall will be way closer to the root, we will be well below the 127 characters limit.
  - Perl-5.16.3-goolf-1.4.10-bare.eb
  - Perl-5.16.3-ictce-5.3.0.eb # Perl problem comes from the shebang being too long. This problem should disappear at release since the rootinstall will be way closer to the root, we will be well below the 127 characters limit.
  - Perl-5.16.3-ictce-5.3.0-bare.eb
  - PyQt-4.11.3-ictce-7.3.5-Python-2.7.10.eb
  - Python-2.7.6-goolf-1.4.10.eb
  - Python-2.7.5-ictce-5.3.0.eb
  - Python-2.7.10-ictce-7.3.5.eb
  - Python-2.7.10-ictce-7.3.5-bare.eb
  - Python-3.3.2-goolf-1.4.10.eb # Not available anymore due to extension not available anymore at this version (nose)
  - Python-3.3.2-ictce-5.3.0.eb # Not available anymore due to extension not available anymore at this version (nose)
  - Python-3.4.3-ictce-7.3.5.eb
  - Python-3.4.3-ictce-7.3.5-bare.eb
  - QuantumESPRESSO-5.0.2-goolf-1.4.10.eb
  - QuantumESPRESSO-5.0.2-goolf-1.4.10-hybrid.eb
  - QuantumESPRESSO-5.0.2-ictce-5.3.0.eb
  - QuantumESPRESSO-5.0.2-ictce-5.3.0-hybrid.eb
  - QuantumESPRESSO-5.1.2-ictce-7.3.5.eb
  - R-3.0.2-goolf-1.4.10.eb # Download Java sources separately (normal behavior in EasyBuild) + Easyconfig changes: (Rniftilib: ext_options->rforge_options 0.0-32->0.0-35) (Rsamtools: 1.14.1->1.14.3) (pim: 1.1.5.4->1.1.5.6) + IRanges not downloading correctly
  - R-3.0.2-ictce-5.3.0.eb # Download Java sources separately (normal behavior in EasyBuild) + IRanges, Biostrings, GenomicRanges, graph, not downloading correctly
  - R-3.0.2-ictce-5.3.0-bare.eb # Download Java sources separately (normal behavior in EasyBuild)
  - R-3.2.0-ictce-7.3.5-bare.eb
  - R-3.2.0-ictce-7.3.5-Rmpi.eb
  - SAMtools-0.1.19-goolf-1.4.10.eb
  - SAMtools-0.1.19-ictce-5.3.0.eb
  - SAMtools-1.2-ictce-5.3.0.eb
  - SAMtools-1.2-goolf-1.4.10.eb
  - scipy-0.13.0-goolf-1.4.10-Python-2.7.3.eb 
  - scipy-0.12.0-ictce-5.3.0-Python-2.7.3.eb # download source manually scipy-0.12.0.tar.gz
  - Valgrind-3.8.1-goolf-1.4.10.eb # Following fix in easyconfig: preconfigopts = 'export CFLAGS="-I/usr/include/x86_64-linux-gnu $CFLAGS" && '
  - XCrySDen-1.5.53-goolf-1.4.10.eb # changing dependencies in XCrySDen to libXmu-dev and in Mesa to libX11-dev x11proto-core-dev libXdamage-dev libXext-dev libXfixes-dev + downloading MesaLib sources manually.
  - XCrySDen-1.5.53-ictce-5.3.0.eb # changing dependencies in XCrySDen to libXmu-dev and in Mesa to libX11-dev x11proto-core-dev libXdamage-dev libXext-dev libXfixes-dev + downloading MesaLib sources manually.
  - MATLAB-2013a.eb # Sources to get manually + Provide license key in the MATLAB2013a_KEY environment variable
  - MATLAB-2013b.eb # Sources to get manually + Provide license key in the MATLAB2013b_KEY environment variable
  - MATLAB-2014a.eb # Sources to get manually + Provide license key in the MATLAB2014a_KEY environment variable
  - TotalView-8.12.0-0-linux-x86-64.eb # sources to get manually
  - ABAQUS-6.11.1.eb # Sources downloaded manually
  - ABAQUS-6.14.2.eb # Sources downloaded manually
  # Not ANYMORE AGAIN. Doesn't make any sense - matplotlib-1.3.0-ictce-5.3.0-Python-2.7.5.eb # Works AGAIN (at least when built at the END of the process. Will try to build it there again and see if the problem occurs one again (A missing module dependency ?))
ulhpc:
  - Autoconf-2.69-gcccuda-2.6.10.eb
  - Automake-1.14-gcccuda-2.6.10.eb
  - Automake-1.14.1-GCC-4.8.2.eb
  - Boost-1.55.0.eb
  - CMake-3.0.0-GCC-4.8.3.eb
  - CUDA-5.5.22-GCC-4.8.2.eb
lcsb:
  - BEDTools-2.23.0-goolf-1.4.10.eb
  - BWA-0.7.12-goolf-1.4.10.eb
  - GATK-3.3-0-Java-1.7.0_21.eb
  - picard-1.130.eb
  - FastQC-0.11.2.eb
  - TopHat-2.0.14-goolf-1.4.10.eb
  - TopHat-2.0.14-ictce-5.3.0.eb
  - EMBOSS-6.6.0-nodep-goolf-1.4.10.eb
  - Cython-0.22-goolf-1.4.10-Python-2.7.3.eb
  - Circos-0.64-ictce-5.5.0-Perl-5.18.2.eb
  - MUSCLE-3.8.31-goolf-1.4.10.eb
  - bam2fastq-1.1.0-goolf-1.4.10.eb
  - parallel-20130122-goolf-1.4.10.eb
  - BLAST-2.2.26-Linux_x86_64.eb
  - BLAST+-2.2.28-goolf-1.4.10.eb
  - BLAST+-2.2.28-goolf-1.4.10-Python-2.7.3.eb
  - pandas-0.16.0-goolf-1.4.10-Python-3.3.2.eb
  - Trinity-2.0.6-goolf-1.4.10.eb

# To create a "all" software set, use this command: "find -name "*.eb" -exec basename {} \; | sed "s/^/  - /g" > swsets.yaml"
